In [97]:
with open('One.txt') as mytext:
    words_one = mytext.read().lower().split()
    uni_words_one = set(words_one)

In [98]:
uni_words_one

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [99]:
with open('Two.txt') as mytext:
    words_two = mytext.read().lower().split()
    uni_words_two = set(words_two)

In [100]:
uni_words_two

{'a',
 'about',
 'catching',
 'fun',
 'is',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [101]:
all_unique_words = set()
all_unique_words.update(uni_words_one)
all_unique_words.update(uni_words_two)

In [102]:
all_unique_words

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [103]:
full_vocab = dict()
i=0
for word in all_unique_words:
    full_vocab[word] = i
    i = i + 1

In [104]:
full_vocab

{'popular': 0,
 'this': 1,
 'is': 2,
 'furry': 3,
 'waves': 4,
 'about': 5,
 'canine': 6,
 'animals': 7,
 'water': 8,
 'story': 9,
 'sport': 10,
 'a': 11,
 'fun': 12,
 'dogs': 13,
 'surfing': 14,
 'catching': 15,
 'pets': 16,
 'our': 17,
 'are': 18}

In [105]:
one_freq = [0]*len(full_vocab)
two_freq = [0]*len(full_vocab)
all_words = ['']*len(full_vocab)

In [106]:
one_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [107]:
with open('One.txt') as f:
    one_text = f.read().lower().split()

In [108]:
for word in one_text:
    word_ind = full_vocab[word]
    one_freq[word_ind] += 1

In [109]:
one_freq

[0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 2, 0, 0, 1, 1, 1]

In [110]:
with open('two.txt') as f:
    two_text = f.read().lower().split()

In [111]:
for word in two_text:
    word_ind = full_vocab[word]
    two_freq[word_ind] += 1

In [112]:
two_freq

[1, 1, 3, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 2, 1, 0, 0, 0]

In [113]:
all_words

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [114]:
for word in full_vocab:
    word_ind = full_vocab[word]
    all_words[word_ind] = word

In [115]:
all_words

['popular',
 'this',
 'is',
 'furry',
 'waves',
 'about',
 'canine',
 'animals',
 'water',
 'story',
 'sport',
 'a',
 'fun',
 'dogs',
 'surfing',
 'catching',
 'pets',
 'our',
 'are']

In [116]:
import pandas as pd
bow = pd.DataFrame(data=[one_freq, two_freq], columns=all_words)

In [117]:
bow

popular  this  is  furry  waves  about  canine  animals  water  story  \
0        0     1   1      1      0      1       1        1      0      1   
1        1     1   3      0      1      1       0        0      1      1   

   sport  a  fun  dogs  surfing  catching  pets  our  are  
0      0  1    0     2        0         0     1    1    1  
1      1  1    1     0        2         1     0    0    0

In [118]:
text = ['This is a line', 'This is another line', 'Completely different line']

In [119]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

In [120]:
cv = CountVectorizer()

In [121]:
sparse_matrix = cv.fit_transform(text)

In [122]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [123]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [124]:
tfidf = TfidfTransformer()

In [125]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [127]:
results = tfidf.fit_transform(sparse_matrix)

In [129]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [130]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [131]:
tv = TfidfVectorizer()

In [132]:
tv_results = tv.fit_transform(text)

In [134]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])